name: On push to feature and release branches

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"
permissions:
  contents: read

jobs:
  unit_test_from_local:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Add type_hint_checker to PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$PWD/type_hint_checker" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          pytest tests/test_unit_tests.py
  command_line_tests_from_local:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
    - name: Test with pytest
      run: |
        python -m pytest tests/test_command_line.py
  test_pre_commit_from_local:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install pre-commit pytest
          pip install .
          pre-commit install -c tests/configs/strict.yaml
          pre-commit run --all-files -c tests/configs/strict.yaml || true #  For pre-commit initialization
      - name: Test with pytest
        run: |
          python -m pytest tests/test_pre_commit.py
