name: Feature tests

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Send feature dispatch
      run: |
        curl -XPOST -u "PaulinaPacyna:${{secrets.PAT_TOKEN}}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Content-Type: application/json" https://api.github.com/repos/PaulinaPacyna/test_annotation_checker/dispatches \
        --data '{"event_type": "feature"}' \
        --fail-with-body