name: Unit tests

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test_from_local:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Add type_hint_checker to PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$PWD/type_hint_checker" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
          pytest tests/test_unit_tests.py
